//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowFormAppClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getStationsInfos", ReplyAction="http://tempuri.org/IService1/getStationsInfosResponse")]
        string getStationsInfos(string contractName, string stationName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getStationsInfos", ReplyAction="http://tempuri.org/IService1/getStationsInfosResponse")]
        System.Threading.Tasks.Task<string> getStationsInfosAsync(string contractName, string stationName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getStationsNames", ReplyAction="http://tempuri.org/IService1/getStationsNamesResponse")]
        string[] getStationsNames(string contractName, string stationName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getStationsNames", ReplyAction="http://tempuri.org/IService1/getStationsNamesResponse")]
        System.Threading.Tasks.Task<string[]> getStationsNamesAsync(string contractName, string stationName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetContractsNames", ReplyAction="http://tempuri.org/IService1/GetContractsNamesResponse")]
        string[] GetContractsNames();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetContractsNames", ReplyAction="http://tempuri.org/IService1/GetContractsNamesResponse")]
        System.Threading.Tasks.Task<string[]> GetContractsNamesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WindowFormAppClient.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WindowFormAppClient.ServiceReference1.IService1>, WindowFormAppClient.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string getStationsInfos(string contractName, string stationName) {
            return base.Channel.getStationsInfos(contractName, stationName);
        }
        
        public System.Threading.Tasks.Task<string> getStationsInfosAsync(string contractName, string stationName) {
            return base.Channel.getStationsInfosAsync(contractName, stationName);
        }
        
        public string[] getStationsNames(string contractName, string stationName) {
            return base.Channel.getStationsNames(contractName, stationName);
        }
        
        public System.Threading.Tasks.Task<string[]> getStationsNamesAsync(string contractName, string stationName) {
            return base.Channel.getStationsNamesAsync(contractName, stationName);
        }
        
        public string[] GetContractsNames() {
            return base.Channel.GetContractsNames();
        }
        
        public System.Threading.Tasks.Task<string[]> GetContractsNamesAsync() {
            return base.Channel.GetContractsNamesAsync();
        }
    }
}
