//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestAndSoapWSLabClientMonitoring.ServiceReferenceMonitoring {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceMonitoring.IServiceMonitoring")]
    public interface IServiceMonitoring {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMonitoring/getNumberOfRequests", ReplyAction="http://tempuri.org/IServiceMonitoring/getNumberOfRequestsResponse")]
        int getNumberOfRequests();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMonitoring/getNumberOfRequests", ReplyAction="http://tempuri.org/IServiceMonitoring/getNumberOfRequestsResponse")]
        System.Threading.Tasks.Task<int> getNumberOfRequestsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceMonitoringChannel : RestAndSoapWSLabClientMonitoring.ServiceReferenceMonitoring.IServiceMonitoring, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceMonitoringClient : System.ServiceModel.ClientBase<RestAndSoapWSLabClientMonitoring.ServiceReferenceMonitoring.IServiceMonitoring>, RestAndSoapWSLabClientMonitoring.ServiceReferenceMonitoring.IServiceMonitoring {
        
        public ServiceMonitoringClient() {
        }
        
        public ServiceMonitoringClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceMonitoringClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceMonitoringClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceMonitoringClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int getNumberOfRequests() {
            return base.Channel.getNumberOfRequests();
        }
        
        public System.Threading.Tasks.Task<int> getNumberOfRequestsAsync() {
            return base.Channel.getNumberOfRequestsAsync();
        }
    }
}
